---
pipeline:
  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/toladata/tolarelease_server
    file: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]

  trigger-deployment:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    verbose: true
    drone_server: http://drone.tola.io
    drone_token: $DRONE_TOKEN
    secrets: [DRONE_TOKEN]
    repo: toladata/deployment
    branch: master
    deploy_to: marathon
    params: "APP_ID=/tolareleaseserver,APP_GROUP=toladata,APP_NAME=TolaReleaseServer,APP_BRANCH=${DRONE_COMMIT_BRANCH},APP_COMMIT=${DRONE_COMMIT_SHA},APP_TAG=${DRONE_TAG},APP_IMAGE=registry.tola.io/toladata/tolarelease_server:${DRONE_COMMIT_SHA}"
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]
