version: '2'
services:
  web:
    build: .
    container_name: tolarelease_server
    image: tolarelease_server
    volumes:
      - /tmp/
    depends_on:
      - db
    ports:
      - '5000:80'
    entrypoint: ./scripts/wait.sh $TOLA_DB_HOST:5432 -- npm start
