version: '2'
services:
  web:
    build: .
    container_name: tolarelease_server
    image: tolarelease_server
    volumes:
      - /tmp/
    depends_on:
      - db
    ports:
      - '5000:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
